update_check = false

enter_accept = true
search_mode = "fuzzy"

history_filter = [
  "^export .*(TOKEN|KEY|SECRET)=",
  "--token=",
  "--password=",
  "--api-key=",
]

[daemon]
autostart = true

[keymap.emacs]
"alt-j" = "select-next"
"alt-k" = "select-previous"

[sync]
records = true
